services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php-apache:
    image: php:apache
    restart: always
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html
    ports:
      - "8081:80"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "8080:80"
